# Generated by Django 5.2.5 on 2025-11-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_alter_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-puplished_date']},
        ),
    ]
