# Generated by Django 5.2.5 on 2026-01-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_alter_post_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rasmlar/'),
        ),
    ]
