# Generated by Django 5.2.5 on 2026-01-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_kategoriya_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='puplished_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Publish date'),
        ),
    ]
